memory_limit=${PHP_MEMORY_LIMIT}
upload_max_filesize=${PHP_UPLOAD_MAX_FILESIZE}
post_max_size=${PHP_POST_MAX_SIZE}
expose_php=0
opcache.enable=1
opcache.enable_cli=1
opcache.validate_timestamps=1
opcache.memory_consumption=96
opcache.interned_strings_buffer=12
opcache.max_accelerated_files=10000
realpath_cache_size=4096K
realpath_cache_ttl=600
